name: tabbed_view
description: Flutter widget inspired by the classic Desktop-style tab component. Supports customizable themes.
version: 1.22.1
repository: https://github.com/caduandrade/tabbed_view
homepage: https://caduandrade.github.io/tabbed_view

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0